<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function findAllOrdered()
    {
        /**
         * Raw way of querying database using Doctrine
         *
         * $dql = 'SELECT cat FROM AppBundle\Entity\Category cat ORDER BY cat.name DESC';
         * $query = $this->getEntityManager()->createQuery($dql);
         */
        $qb = $this->createQueryBuilder('cat')
            ->addOrderBy('cat.name', 'DESC');

        /** This is how we can re use queries */
        $this->addFortuneCookieJoinAndSelect($qb);
        $query = $qb->getQuery();

        /**
         * Print DQL from CreateQueryBuilder
         *
         * $query->getDQL()
         */

        return $query->execute();
    }

    public function search($searchTerm)
    {
        $qb = $this->createQueryBuilder('cat')
            ->andWhere(
                'cat.name LIKE :searchTerm 
                OR cat.iconKey LIKE :searchTerm
                OR fc.fortune LIKE :searchTerm'
            )
            ->setParameter('searchTerm', '%'.$searchTerm.'%');
        /** This is how we can re use queries */
        $this->addFortuneCookieJoinAndSelect($qb);

        return $qb->getQuery()->execute();
    }

    public function findWithFortunesJoin($id)
    {
        $qb = $this->createQueryBuilder('cat')
            ->andWhere('cat.id = :id')
            ->setParameter('id', $id);

        /** This is how we can re use queries */
        $this->addFortuneCookieJoinAndSelect($qb);

        return $qb->getQuery()->getOneOrNullResult();
    }

    private function addFortuneCookieJoinAndSelect(QueryBuilder $qb)
    {
        return $qb->leftJoin('cat.fortuneCookies', 'fc')
            ->addSelect('fc');
    }
}
